channels:
- conda-forge
dependencies:
- python=3.11.2
- pip<=25.3
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.3.3
  - psutil==5.9.5
  - pyarrow==15.0.2
  - scikit-learn==1.7.2
  - scipy==1.16.2
name: mlflow-env